name: cameron_alison_theta_decoding
channels:
- defaults
- conda-forge
- edeno
dependencies:
- "python>=3.6"
- loren_frank_data_processing
- ripple_detection
- replay_trajectory_classification
- spectral_connectivity
- numpy
- numba
- scipy
- scikit-learn
- matplotlib
- xarray
- pandas
- seaborn
- dask
- tqdm
- statsmodels
- patsy
- jupyter
- jupyterlab
- nb_conda
- setuptools
- pytest
- pytest-cov
- coveralls
- pip:
  - nb_black
